spring: 
    jpa:  
        hibernate: 
            ddl-auto: create
    datasource: 
        url: jdbc:postgresql://192.168.100.103:5432/dvdrental
        username: test
        password: test
        hikari: 
            connection-timeout: 20000
            maximum-pool-size: 5

