package com.shinear.dvdrental.model;


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import java.io.Serializable;
import java.util.Date;

/**
 * generated by Generate POJOs.groovy 
 * <p>Date: Mon Jan 11 00:34:39 CST 2021.</p>
 *
 * @author Kevin
 */
@Entity
@Table ( name ="category" )
public class Category implements Serializable {


	private static final long serialVersionUID = 6343956198101314660L;

	@Id
 	@Column(name = "category_id" )
	private Long   categoryId;

 	@Column(name = "name" )
	private String   name;

 	@Column(name = "last_update" )
	private Date   lastUpdate;

	public Long  getCategoryId() {
		return this.categoryId;
	}

	public void setCategoryId(Long categoryId) {
		this.categoryId=categoryId;
	}

	public String  getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name=name;
	}

	public Date  getLastUpdate() {
		return this.lastUpdate;
	}

	public void setLastUpdate(Date lastUpdate) {
		this.lastUpdate=lastUpdate;
	}

}
