package com.shinear.dvdrental.model;


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import java.io.Serializable;
import java.util.Date;

/**
 * generated by Generate POJOs.groovy 
 * <p>Date: Mon Jan 11 00:34:39 CST 2021.</p>
 *
 * @author Kevin
 */
@Entity
@Table ( name ="country" )
public class Country implements Serializable {


	private static final long serialVersionUID = 4763063775968587304L;

	@Id
 	@Column(name = "country_id" )
	private Long   countryId;

 	@Column(name = "country" )
	private String   country;

 	@Column(name = "last_update" )
	private Date   lastUpdate;

	public Long  getCountryId() {
		return this.countryId;
	}

	public void setCountryId(Long countryId) {
		this.countryId=countryId;
	}

	public String  getCountry() {
		return this.country;
	}

	public void setCountry(String country) {
		this.country=country;
	}

	public Date  getLastUpdate() {
		return this.lastUpdate;
	}

	public void setLastUpdate(Date lastUpdate) {
		this.lastUpdate=lastUpdate;
	}

}
