package com.shinear.dvdrental.model;


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import java.io.Serializable;
import java.util.Date;

/**
 * generated by Generate POJOs.groovy 
 * <p>Date: Mon Jan 11 00:34:39 CST 2021.</p>
 *
 * @author Kevin
 */
@Entity
@Table ( name ="inventory" )
public class Inventory implements Serializable {


	private static final long serialVersionUID = 7745746669057924560L;

     @Id
 	@Column(name = "inventory_id" )
	private Long   inventoryId;
	@Id
 	@Column(name = "film_id" )
	private Integer   filmId;
	@Id
 	@Column(name = "store_id" )
	private Integer   storeId;

 	@Column(name = "last_update" )
	private Date   lastUpdate;

	public Long  getInventoryId() {
		return this.inventoryId;
	}

	public void setInventoryId(Long inventoryId) {
		this.inventoryId=inventoryId;
	}

	public Integer  getFilmId() {
		return this.filmId;
	}

	public void setFilmId(Integer filmId) {
		this.filmId=filmId;
	}

	public Integer  getStoreId() {
		return this.storeId;
	}

	public void setStoreId(Integer storeId) {
		this.storeId=storeId;
	}

	public Date  getLastUpdate() {
		return this.lastUpdate;
	}

	public void setLastUpdate(Date lastUpdate) {
		this.lastUpdate=lastUpdate;
	}

}
