package com.shinear.dvdrental.entity;

import javax.persistence.Column;
import javax.persistence.Table;
import java.io.Serializable;
import java.util.Date;

/**
 * generated by Generate POJOs.groovy 
 * <p>Date: Mon Jan 11 00:34:39 CST 2021.</p>
 *
 * @author Kevin
 */

@Table ( name ="city" )
public class CityDO implements Serializable {


	private static final long serialVersionUID = 1288834972064935647L;


 	@Column(name = "city_id" )
	private Long   cityId;

 	@Column(name = "city" )
	private String   city;

 	@Column(name = "country_id" )
	private Integer   countryId;

 	@Column(name = "last_update" )
	private Date   lastUpdate;

	public Long  getCityId() {
		return this.cityId;
	}

	public void setCityId(Long cityId) {
		this.cityId=cityId;
	}

	public String  getCity() {
		return this.city;
	}

	public void setCity(String city) {
		this.city=city;
	}

	public Integer  getCountryId() {
		return this.countryId;
	}

	public void setCountryId(Integer countryId) {
		this.countryId=countryId;
	}

	public Date  getLastUpdate() {
		return this.lastUpdate;
	}

	public void setLastUpdate(Date lastUpdate) {
		this.lastUpdate=lastUpdate;
	}

}
