package com.shinear.dvdrental.entity;

import javax.persistence.Column;
import javax.persistence.Table;
import java.io.Serializable;
import java.util.Date;

/**
 * generated by Generate POJOs.groovy 
 * <p>Date: Mon Jan 11 00:34:39 CST 2021.</p>
 *
 * @author Kevin
 */

@Table ( name ="customer" )
public class CustomerDO implements Serializable {


	private static final long serialVersionUID = 4607906738957942728L;


 	@Column(name = "customer_id" )
	private Long   customerId;

 	@Column(name = "store_id" )
	private Integer   storeId;

 	@Column(name = "first_name" )
	private String   firstName;

 	@Column(name = "last_name" )
	private String   lastName;

 	@Column(name = "email" )
	private String   email;

 	@Column(name = "address_id" )
	private Integer   addressId;

 	@Column(name = "activebool" )
	private Boolean   activebool;

 	@Column(name = "create_date" )
	private Date   createDate;

 	@Column(name = "last_update" )
	private Date   lastUpdate;

 	@Column(name = "active" )
	private Long   active;

	public Long  getCustomerId() {
		return this.customerId;
	}

	public void setCustomerId(Long customerId) {
		this.customerId=customerId;
	}

	public Integer  getStoreId() {
		return this.storeId;
	}

	public void setStoreId(Integer storeId) {
		this.storeId=storeId;
	}

	public String  getFirstName() {
		return this.firstName;
	}

	public void setFirstName(String firstName) {
		this.firstName=firstName;
	}

	public String  getLastName() {
		return this.lastName;
	}

	public void setLastName(String lastName) {
		this.lastName=lastName;
	}

	public String  getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email=email;
	}

	public Integer  getAddressId() {
		return this.addressId;
	}

	public void setAddressId(Integer addressId) {
		this.addressId=addressId;
	}

	public Boolean  getActivebool() {
		return this.activebool;
	}

	public void setActivebool(Boolean activebool) {
		this.activebool=activebool;
	}

	public Date  getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate=createDate;
	}

	public Date  getLastUpdate() {
		return this.lastUpdate;
	}

	public void setLastUpdate(Date lastUpdate) {
		this.lastUpdate=lastUpdate;
	}

	public Long  getActive() {
		return this.active;
	}

	public void setActive(Long active) {
		this.active=active;
	}

}
