package com.shinear.dvdrental.entity;

import javax.persistence.Column;
import javax.persistence.Table;
import java.io.Serializable;
import java.util.Date;

/**
 * generated by Generate POJOs.groovy 
 * <p>Date: Mon Jan 11 00:34:39 CST 2021.</p>
 *
 * @author Kevin
 */

@Table ( name ="film_actor" )
public class Film_ActorDO implements Serializable {


	private static final long serialVersionUID = 7714553180145759954L;


 	@Column(name = "actor_id" )
	private Integer   actorId;

 	@Column(name = "film_id" )
	private Integer   filmId;

 	@Column(name = "last_update" )
	private Date   lastUpdate;

	public Integer  getActorId() {
		return this.actorId;
	}

	public void setActorId(Integer actorId) {
		this.actorId=actorId;
	}

	public Integer  getFilmId() {
		return this.filmId;
	}

	public void setFilmId(Integer filmId) {
		this.filmId=filmId;
	}

	public Date  getLastUpdate() {
		return this.lastUpdate;
	}

	public void setLastUpdate(Date lastUpdate) {
		this.lastUpdate=lastUpdate;
	}

}
