package com.shinear.dvdrental.entity;

import javax.persistence.Column;
import javax.persistence.Table;
import java.io.Serializable;
import java.util.Date;

/**
 * generated by Generate POJOs.groovy 
 * <p>Date: Mon Jan 11 00:34:39 CST 2021.</p>
 *
 * @author Kevin
 */

@Table ( name ="language" )
public class LanguageDO implements Serializable {


	private static final long serialVersionUID = 5870577787512245734L;


 	@Column(name = "language_id" )
	private Long   languageId;

 	@Column(name = "name" )
	private String   name;

 	@Column(name = "last_update" )
	private Date   lastUpdate;

	public Long  getLanguageId() {
		return this.languageId;
	}

	public void setLanguageId(Long languageId) {
		this.languageId=languageId;
	}

	public String  getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name=name;
	}

	public Date  getLastUpdate() {
		return this.lastUpdate;
	}

	public void setLastUpdate(Date lastUpdate) {
		this.lastUpdate=lastUpdate;
	}

}
