package com.shinear.dvdrental.entity;

import javax.persistence.Column;
import javax.persistence.Table;
import java.io.Serializable;
import java.util.Date;

/**
 * generated by Generate POJOs.groovy 
 * <p>Date: Mon Jan 11 00:34:39 CST 2021.</p>
 *
 * @author Kevin
 */

@Table ( name ="payment" )
public class PaymentDO implements Serializable {


	private static final long serialVersionUID = 5990378332105797650L;


 	@Column(name = "payment_id" )
	private Long   paymentId;

 	@Column(name = "customer_id" )
	private Integer   customerId;

 	@Column(name = "staff_id" )
	private Integer   staffId;

 	@Column(name = "rental_id" )
	private Long   rentalId;

 	@Column(name = "amount" )
	private String   amount;

 	@Column(name = "payment_date" )
	private Date   paymentDate;

	public Long  getPaymentId() {
		return this.paymentId;
	}

	public void setPaymentId(Long paymentId) {
		this.paymentId=paymentId;
	}

	public Integer  getCustomerId() {
		return this.customerId;
	}

	public void setCustomerId(Integer customerId) {
		this.customerId=customerId;
	}

	public Integer  getStaffId() {
		return this.staffId;
	}

	public void setStaffId(Integer staffId) {
		this.staffId=staffId;
	}

	public Long  getRentalId() {
		return this.rentalId;
	}

	public void setRentalId(Long rentalId) {
		this.rentalId=rentalId;
	}

	public String  getAmount() {
		return this.amount;
	}

	public void setAmount(String amount) {
		this.amount=amount;
	}

	public Date  getPaymentDate() {
		return this.paymentDate;
	}

	public void setPaymentDate(Date paymentDate) {
		this.paymentDate=paymentDate;
	}

}
