package com.shinear.dvdrental.entity;

import javax.persistence.Column;
import javax.persistence.Table;
import java.io.Serializable;
import java.util.Date;

/**
 * generated by Generate POJOs.groovy 
 * <p>Date: Mon Jan 11 00:34:39 CST 2021.</p>
 *
 * @author Kevin
 */

@Table ( name ="rental" )
public class RentalDO implements Serializable {


	private static final long serialVersionUID = 5560169397603180852L;


 	@Column(name = "rental_id" )
	private Long   rentalId;

 	@Column(name = "rental_date" )
	private Date   rentalDate;

 	@Column(name = "inventory_id" )
	private Long   inventoryId;

 	@Column(name = "customer_id" )
	private Integer   customerId;

 	@Column(name = "return_date" )
	private Date   returnDate;

 	@Column(name = "staff_id" )
	private Integer   staffId;

 	@Column(name = "last_update" )
	private Date   lastUpdate;

	public Long  getRentalId() {
		return this.rentalId;
	}

	public void setRentalId(Long rentalId) {
		this.rentalId=rentalId;
	}

	public Date  getRentalDate() {
		return this.rentalDate;
	}

	public void setRentalDate(Date rentalDate) {
		this.rentalDate=rentalDate;
	}

	public Long  getInventoryId() {
		return this.inventoryId;
	}

	public void setInventoryId(Long inventoryId) {
		this.inventoryId=inventoryId;
	}

	public Integer  getCustomerId() {
		return this.customerId;
	}

	public void setCustomerId(Integer customerId) {
		this.customerId=customerId;
	}

	public Date  getReturnDate() {
		return this.returnDate;
	}

	public void setReturnDate(Date returnDate) {
		this.returnDate=returnDate;
	}

	public Integer  getStaffId() {
		return this.staffId;
	}

	public void setStaffId(Integer staffId) {
		this.staffId=staffId;
	}

	public Date  getLastUpdate() {
		return this.lastUpdate;
	}

	public void setLastUpdate(Date lastUpdate) {
		this.lastUpdate=lastUpdate;
	}

}
